version: '3.8'
services:
  discord-bot:
    build: 
        context: .
        dockerfile: ArmaforcesMissionBot/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
        TZ: "Europe/Warsaw"
  web:
    build:
        context: .
        dockerfile: ArmaforcesMissionBotWeb/Dockerfile
    ports:
        - "8080:80"
        - "10443:443"
    env_file: .env
    environment:
        TZ: "Europe/Warsaw"
