version: '3.8'
services:
  discord-bot:
    build: 
        context: .
        dockerfile: ArmaForces.Boderator.BotService/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
        TZ: "Europe/Warsaw"
